ALTER TABLE ALLOCATIONS_NAISSANCE ADD COLUMN FK_VERSEMENTS BIGINT;

ALTER TABLE ALLOCATIONS_NAISSANCE
    ADD CONSTRAINT FK_AN_VERSEMENTS FOREIGN KEY (FK_VERSEMENTS) REFERENCES VERSEMENTS(NUMERO);

-- Lie les allocations de naissance existantes aux versements par NUMERO correspondant
UPDATE ALLOCATIONS_NAISSANCE
SET FK_VERSEMENTS = NUMERO
WHERE NUMERO IN (SELECT NUMERO FROM VERSEMENTS);
